# This workflow defines a simple CI/CD pipeline with three stages: build, test, and deploy.

name: Simple CI/CD Pipeline

# Define the events that trigger the workflow
on:
  push:
    branches:
      - main  # Trigger the workflow on push events to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests targeting the 'main' branch

# Define the jobs that will be executed as part of the workflow
jobs:
  # The 'build' job
  build:
    runs-on: ubuntu-latest  # Specifies the virtual environment for the job

    steps:
      # Step to checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step to print "Hello World" to indicate the build stage
      - name: Print Hello World
        run: echo "Hello World - Build Stage"

  # The 'test' job
  test:
    runs-on: ubuntu-latest  # Specifies the virtual environment for the job
    needs: build  # This job depends on the successful completion of the 'build' job

    steps:
      # Step to print "Hello World" to indicate the test stage
      - name: Print Hello World
        run: echo "Hello World - Test Stage"

  # The 'deploy' job
  deploy:
    runs-on: ubuntu-latest  # Specifies the virtual environment for the job
    needs: test  # This job depends on the successful completion of the 'test' job

    steps:
      # Step to print "Hello World" to indicate the deploy stage
      - name: Print Hello World
        run: echo "Hello World - Deploy Stage"
